[project]
name = "rl-repo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium[mujoco]>=1.1.1",
    "ipython>=8.35.0",
    "tensorboard>=2.19.0",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
]
